name: Send Daily Voting Reminders

on:
  schedule:
    # Run every day at 10:00 AM UTC (adjust timezone as needed)
    # For Argentina (UTC-3), this runs at 7:00 AM local time
    - cron: '0 10 * * *'
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  send-reminders:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send daily reminders
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json" \
            "${{ secrets.APP_URL }}/api/send-daily-reminders"
        
      - name: Log completion
        run: echo "Daily reminders job completed at $(date)"

# Alternative schedule options (uncomment the one you prefer):
# 
# Every day at 8:00 AM UTC (5:00 AM in Argentina):
# - cron: '0 8 * * *'
#
# Every day at 12:00 PM UTC (9:00 AM in Argentina):  
# - cron: '0 12 * * *'
#
# Only on weekdays (Monday-Friday) at 10:00 AM UTC:
# - cron: '0 10 * * 1-5'
#
# Twice a day (morning and evening):
# - cron: '0 10,18 * * *'